/**
 * Diagnóstico Empresarial APAS — questionário V3 (texto de trabalho fornecido pela APAS)
 * e parâmetros V1 do motor (heurística calibrável — NÃO é validação científica).
 *
 * Este arquivo é a definição de referência usada para carregar/restaurar a configuração
 * no banco. Em produção o motor lê SEMPRE do banco (tabelas diag_*), que é editável.
 */
import type {
  DiagDimension,
  DiagPattern,
  DiagQuestion,
  DiagStage,
  EngineConfig,
  ScaleOption,
} from "./types";

export const V3_INSTRUMENT = {
  code: "diagnostico-empresarial",
  name: "Diagnóstico Empresarial APAS",
  version: "V3",
  description:
    "Instrumento de diagnóstico organizacional com 70 afirmações em 10 dimensões. Versão de trabalho V3 — perguntas, pesos e regras ficam em configuração para calibração antes de uso comercial.",
} as const;

export const V3_SCALE: ScaleOption[] = [
  { value: 1, label: "Discordo totalmente", short: "1" },
  { value: 2, label: "Discordo parcialmente", short: "2" },
  { value: 3, label: "Nem concordo, nem discordo", short: "3" },
  { value: 4, label: "Concordo parcialmente", short: "4" },
  { value: 5, label: "Concordo totalmente", short: "5" },
  { value: null, label: "Não se aplica", short: "N/A" },
];

/** Pesos por eixo são parâmetros V1 calibráveis (não representam validação empírica). */
export const V3_DIMENSIONS: DiagDimension[] = [
  { code: "L", name: "Liderança", sort_order: 1, axis_weights: { flexibilidade: 1, controle: 1, integracao: 1.5, sustentacao: 1.5 } },
  { code: "E", name: "Estratégia", sort_order: 2, axis_weights: { flexibilidade: 1, controle: 1, sustentacao: 2 } },
  { code: "G", name: "Gestão", sort_order: 3, axis_weights: { controle: 3 } },
  { code: "P", name: "Processos", sort_order: 4, axis_weights: { controle: 3, sustentacao: 1 } },
  { code: "PE", name: "Pessoas", sort_order: 5, axis_weights: { integracao: 2, sustentacao: 2 } },
  { code: "C", name: "Cultura", sort_order: 6, axis_weights: { flexibilidade: 1.5, integracao: 2.5 } },
  { code: "CO", name: "Comunicação", sort_order: 7, axis_weights: { integracao: 3 } },
  { code: "M", name: "Mercado e Clientes", sort_order: 8, axis_weights: { flexibilidade: 2 } },
  { code: "I", name: "Inovação e Adaptabilidade", sort_order: 9, axis_weights: { flexibilidade: 3 } },
  { code: "R", name: "Resultados e Sustentabilidade", sort_order: 10, axis_weights: { controle: 2, sustentacao: 3 } },
];

type Q = [code: string, dim: string, weight: 1 | 2 | 3, text: string, direction?: "inverse"];

const RAW: Q[] = [
  ["L01", "L", 2, "As principais decisões da empresa ainda dependem diretamente do proprietário ou principal líder.", "inverse"],
  ["L02", "L", 3, "Os gestores possuem autonomia para tomar decisões dentro de suas responsabilidades."],
  ["L03", "L", 2, "Os responsáveis pelas áreas conhecem claramente suas atribuições e limites de decisão."],
  ["L04", "L", 3, "A liderança consegue delegar responsabilidades sem precisar acompanhar cada detalhe da execução."],
  ["L05", "L", 2, "Os líderes são avaliados principalmente pelos resultados de suas áreas."],
  ["L06", "L", 3, "A empresa possui pessoas preparadas para assumir responsabilidades maiores no futuro."],
  ["L07", "L", 2, "Quando ocorre um problema, a liderança busca compreender suas causas antes de definir responsabilidades."],
  ["L08", "L", 3, "A empresa consegue funcionar adequadamente mesmo quando seu principal líder não está presente."],
  ["E01", "E", 2, "A empresa possui objetivos claros para os próximos 12 meses."],
  ["E02", "E", 2, "Os principais líderes sabem quais são as prioridades estratégicas da empresa."],
  ["E03", "E", 2, "A empresa possui metas que podem ser acompanhadas por indicadores."],
  ["E04", "E", 2, "As decisões importantes consideram os objetivos de médio e longo prazo."],
  ["E05", "E", 2, "A empresa conhece claramente seu principal diferencial competitivo."],
  ["E06", "E", 3, "A empresa revisa sua estratégia quando ocorrem mudanças relevantes no mercado."],
  ["E07", "E", 3, "Existe equilíbrio entre aproveitar novas oportunidades e manter o foco no negócio principal."],
  ["G01", "G", 2, "A empresa acompanha regularmente seus principais indicadores de desempenho."],
  ["G02", "G", 2, "Os gestores sabem quais resultados são esperados de suas áreas."],
  ["G03", "G", 2, "Existem reuniões periódicas para acompanhar resultados e definir ações."],
  ["G04", "G", 2, "Problemas recorrentes são registrados e acompanhados até sua solução."],
  ["G05", "G", 2, "A empresa consegue identificar rapidamente quando um resultado está abaixo do esperado."],
  ["G06", "G", 3, "A empresa utiliza informações e indicadores para apoiar decisões importantes."],
  ["G07", "G", 3, "Os gestores conseguem equilibrar as necessidades do curto prazo com os objetivos de longo prazo."],
  ["P01", "P", 2, "Os principais processos da empresa estão claramente definidos."],
  ["P02", "P", 2, "As atividades importantes possuem procedimentos ou padrões conhecidos pela equipe."],
  ["P03", "P", 3, "A empresa consegue manter seus processos funcionando mesmo quando determinadas pessoas estão ausentes."],
  ["P04", "P", 2, "Existem controles suficientes para evitar erros recorrentes."],
  ["P05", "P", 2, "Os processos são revisados quando deixam de atender às necessidades da empresa."],
  ["P06", "P", 2, "A empresa consegue identificar rapidamente onde ocorre um problema dentro de um processo."],
  ["P07", "P", 3, "Existe equilíbrio entre controle dos processos e agilidade na tomada de decisões."],
  ["PE01", "PE", 3, "A empresa possui profissionais preparados para assumir responsabilidades além de suas funções atuais."],
  ["PE02", "PE", 2, "As responsabilidades de cada profissional estão claramente definidas."],
  ["PE03", "PE", 2, "A empresa investe no desenvolvimento de seus colaboradores."],
  ["PE04", "PE", 2, "Os profissionais recebem feedback sobre seu desempenho."],
  ["PE05", "PE", 2, "A empresa possui critérios para identificar profissionais de maior potencial."],
  ["PE06", "PE", 3, "A empresa possui mecanismos para reduzir a dependência de pessoas-chave."],
  ["PE07", "PE", 2, "Os colaboradores compreendem como seu trabalho contribui para os resultados da empresa."],
  ["C01", "C", 2, "As decisões e atitudes da liderança são coerentes com os valores que a empresa declara."],
  ["C02", "C", 3, "Os colaboradores conseguem apresentar problemas à liderança sem receio de consequências injustas."],
  ["C03", "C", 3, "As pessoas têm espaço para apresentar sugestões de melhoria."],
  ["C04", "C", 2, "Quando ocorre um erro, a empresa procura entender o que precisa ser corrigido para evitar sua repetição."],
  ["C05", "C", 2, "A empresa consegue preservar seus valores e práticas positivas mesmo quando cresce."],
  ["C06", "C", 3, "A empresa demonstra disposição para mudar práticas que deixaram de funcionar."],
  ["C07", "C", 2, "Conflitos internos são tratados de forma que permita buscar soluções."],
  ["CO01", "CO", 2, "As informações importantes chegam às pessoas certas no momento adequado."],
  ["CO02", "CO", 2, "Os colaboradores sabem claramente o que a liderança espera deles."],
  ["CO03", "CO", 2, "As decisões importantes são comunicadas de forma clara."],
  ["CO04", "CO", 2, "Existe comunicação eficiente entre diferentes áreas da empresa."],
  ["CO05", "CO", 3, "Informações importantes não ficam concentradas em poucas pessoas."],
  ["CO06", "CO", 2, "Existe abertura para comunicação nos dois sentidos entre liderança e equipe."],
  ["M01", "M", 2, "A empresa acompanha regularmente as necessidades e expectativas dos clientes."],
  ["M02", "M", 2, "A empresa acompanha seus principais concorrentes."],
  ["M03", "M", 3, "A empresa identifica mudanças relevantes no mercado antes que elas afetem significativamente seus resultados."],
  ["M04", "M", 2, "O feedback dos clientes é utilizado para melhorar produtos, serviços ou processos."],
  ["M05", "M", 3, "A empresa consegue adaptar sua oferta quando o comportamento do mercado muda."],
  ["M06", "M", 2, "A empresa possui clareza sobre quais clientes são mais importantes para sua estratégia."],
  ["M07", "M", 2, "A empresa consegue identificar novas oportunidades de mercado sem perder o foco do negócio principal."],
  ["I01", "I", 2, "A empresa estimula novas ideias para melhorar seus resultados."],
  ["I02", "I", 3, "Novas ideias podem ser testadas sem excesso de burocracia."],
  ["I03", "I", 3, "A empresa consegue mudar rapidamente quando uma estratégia deixa de funcionar."],
  ["I04", "I", 2, "A liderança demonstra abertura para novas formas de trabalhar."],
  ["I05", "I", 2, "A empresa acompanha novas tecnologias relevantes para seu segmento."],
  ["I06", "I", 2, "A empresa aprende com experiências anteriores e utiliza esse aprendizado em novas decisões."],
  ["I07", "I", 3, "Existe equilíbrio entre segurança operacional e disposição para experimentar."],
  ["R01", "R", 2, "A empresa acompanha regularmente sua rentabilidade."],
  ["R02", "R", 2, "A empresa possui controle sobre seus principais custos."],
  ["R03", "R", 2, "A empresa acompanha indicadores financeiros relevantes para sua operação."],
  ["R04", "R", 3, "O crescimento da empresa ocorre de forma financeiramente sustentável."],
  ["R05", "R", 3, "A empresa consegue identificar rapidamente problemas que podem comprometer seus resultados."],
  ["R06", "R", 2, "As decisões de crescimento consideram a capacidade financeira e operacional da empresa."],
  ["R07", "R", 3, "A empresa possui condições de sustentar seu modelo de negócio no médio e longo prazo."],
];

export const V3_QUESTIONS: DiagQuestion[] = RAW.map(([code, dim, weight, text, direction], i) => ({
  code,
  dimension_code: dim,
  text,
  weight,
  direction: direction ?? "direct",
  allow_na: true,
  active: true,
  sort_order: i + 1,
}));

/**
 * Estágios de referência conceitual do ciclo de vida organizacional (eixos na ordem
 * Flexibilidade / Controle / Integração / Sustentação). Perfis V1 calibráveis.
 * Não constitui instrumento certificado de terceiros.
 */
export const V1_STAGES: DiagStage[] = [
  {
    code: "namoro",
    name: "Namoro",
    short_label: "Ideia e entusiasmo",
    sort_order: 1,
    axes: { flexibilidade: 85, controle: 20, integracao: 30, sustentacao: 15 },
    is_critical: false,
    auto_release_allowed: true,
    narrative: {
      summary:
        "Fase de concepção: a empresa é sustentada pela visão e pelo entusiasmo do fundador, com pouca estrutura de gestão e baixa previsibilidade de resultados.",
      signals: ["Decisões centralizadas na visão do fundador", "Poucos processos e indicadores formais", "Muita energia em ideias, pouca em execução sistemática"],
      risks: ["Compromisso não se converter em operação real", "Recursos consumidos antes de validar a proposta de valor"],
      focus: ["Traduzir a visão em objetivos concretos de 12 meses", "Definir os primeiros indicadores de acompanhamento", "Validar diferencial competitivo com clientes reais"],
    },
  },
  {
    code: "infancia",
    name: "Infância",
    short_label: "Ação e sobrevivência",
    sort_order: 2,
    axes: { flexibilidade: 45, controle: 30, integracao: 35, sustentacao: 35 },
    is_critical: false,
    auto_release_allowed: true,
    narrative: {
      summary:
        "Fase de operação intensa: a empresa vende e entrega, mas depende fortemente do líder principal, com caixa apertado e gestão reativa.",
      signals: ["Forte dependência do proprietário", "Gestão orientada a urgências", "Fragilidade financeira e de controles"],
      risks: ["Esgotamento do líder", "Mortalidade por falta de caixa", "Crescimento sem base de processos"],
      focus: ["Organizar controle de custos e rentabilidade", "Definir responsabilidades básicas", "Criar rotina mínima de acompanhamento de resultados"],
    },
  },
  {
    code: "toca_toca",
    name: "Toca-Toca",
    short_label: "Crescimento acelerado",
    sort_order: 3,
    axes: { flexibilidade: 90, controle: 40, integracao: 50, sustentacao: 55 },
    is_critical: false,
    auto_release_allowed: true,
    narrative: {
      summary:
        "Fase de crescimento acelerado e oportunista: muitas frentes abertas, confiança elevada e estrutura que não acompanha o ritmo do negócio.",
      signals: ["Múltiplas oportunidades sem critério de foco", "Processos improvisados", "Decisões rápidas com pouca análise"],
      risks: ["Dispersão de foco e recursos", "Erros recorrentes por falta de padrão", "Armadilha do fundador"],
      focus: ["Estabelecer prioridades estratégicas e critérios de foco", "Formalizar os processos essenciais", "Fortalecer gestores intermediários com autonomia"],
    },
  },
  {
    code: "adolescencia",
    name: "Adolescência",
    short_label: "Profissionalização",
    sort_order: 4,
    axes: { flexibilidade: 75, controle: 65, integracao: 70, sustentacao: 65 },
    is_critical: false,
    auto_release_allowed: true,
    narrative: {
      summary:
        "Fase de transição para a gestão profissional: sistemas e delegação avançam, com conflitos naturais entre a cultura empreendedora e a necessidade de estrutura.",
      signals: ["Delegação em construção", "Conflitos entre áreas e entre fundador e gestores", "Indicadores e processos em amadurecimento"],
      risks: ["Divórcio entre fundador e equipe profissional", "Envelhecimento precoce por excesso de controle"],
      focus: ["Alinhar papéis e limites de decisão", "Integrar comunicação entre áreas", "Equilibrar controle e agilidade"],
    },
  },
  {
    code: "plenitude",
    name: "Plenitude",
    short_label: "Equilíbrio e vitalidade",
    sort_order: 5,
    axes: { flexibilidade: 85, controle: 85, integracao: 85, sustentacao: 85 },
    is_critical: false,
    auto_release_allowed: true,
    narrative: {
      summary:
        "Fase de equilíbrio entre flexibilidade e controle: a empresa cresce com previsibilidade, forma líderes e mantém capacidade de adaptação.",
      signals: ["Resultados consistentes e crescimento sustentável", "Processos claros com espaço para inovação", "Sucessão e desenvolvimento de pessoas ativos"],
      risks: ["Acomodação gradual", "Perda de senso de urgência"],
      focus: ["Preservar a disposição para mudar", "Renovar a estratégia periodicamente", "Investir em novos negócios e talentos"],
    },
  },
  {
    code: "estabilidade",
    name: "Estabilidade",
    short_label: "Conforto e previsibilidade",
    sort_order: 6,
    axes: { flexibilidade: 60, controle: 85, integracao: 80, sustentacao: 85 },
    is_critical: false,
    auto_release_allowed: true,
    narrative: {
      summary:
        "Fase de conforto: resultados ainda são bons e a estrutura funciona, mas a empresa começa a perder apetite por mudança e proximidade com o mercado.",
      signals: ["Foco em manutenção do que existe", "Menor investimento em novas ideias", "Reuniões mais sobre passado do que sobre futuro"],
      risks: ["Início silencioso do envelhecimento", "Perda de talentos inquietos"],
      focus: ["Reaproximar a empresa do cliente e do mercado", "Recriar espaço para experimentação", "Estabelecer metas de renovação"],
    },
  },
  {
    code: "aristocracia",
    name: "Aristocracia",
    short_label: "Forma acima do conteúdo",
    sort_order: 7,
    axes: { flexibilidade: 35, controle: 90, integracao: 65, sustentacao: 75 },
    is_critical: false,
    auto_release_allowed: true,
    narrative: {
      summary:
        "Fase em que a aparência e a tradição pesam mais que o desempenho: controles fortes, pouca inovação e distância crescente do mercado.",
      signals: ["Excesso de formalismo", "Dificuldade de mudar práticas antigas", "Perda gradual de competitividade"],
      risks: ["Erosão financeira mascarada por reservas", "Ruptura cultural quando os resultados caem"],
      focus: ["Confrontar dados de mercado e rentabilidade", "Reduzir camadas de controle sem valor", "Retomar iniciativa comercial e inovação"],
    },
  },
  {
    code: "pre_burocracia",
    name: "Pré-Burocracia / Recriminação",
    short_label: "Conflito interno",
    sort_order: 8,
    axes: { flexibilidade: 25, controle: 65, integracao: 30, sustentacao: 45 },
    is_critical: true,
    auto_release_allowed: false,
    narrative: {
      summary:
        "Fase de recriminação: os resultados caem e a energia se volta para dentro — busca de culpados, conflitos e perda de confiança entre liderança e equipe.",
      signals: ["Clima de culpa e defesa", "Comunicação truncada entre áreas", "Saída de pessoas-chave"],
      risks: ["Aceleração da perda de clientes", "Paralisia decisória"],
      focus: ["Restabelecer segurança psicológica e comunicação direta", "Focar poucas prioridades de recuperação", "Recuperar contato com clientes"],
    },
  },
  {
    code: "burocracia",
    name: "Burocracia",
    short_label: "Sistema sem propósito",
    sort_order: 9,
    axes: { flexibilidade: 15, controle: 95, integracao: 25, sustentacao: 35 },
    is_critical: true,
    auto_release_allowed: false,
    narrative: {
      summary:
        "Fase em que regras e procedimentos substituem resultados: a empresa opera para si mesma, com baixa adaptação e pouca conexão com clientes.",
      signals: ["Procedimentos que não geram valor", "Novas ideias barradas por regras", "Desconexão com o mercado"],
      risks: ["Dependência de proteção externa ou de caixa acumulado", "Declínio acelerado quando o ambiente muda"],
      focus: ["Simplificar radicalmente processos", "Redefinir propósito e proposta de valor", "Reconstruir capacidade de decisão e adaptação"],
    },
  },
  {
    code: "declinio",
    name: "Risco crítico de viabilidade (Declínio)",
    short_label: "Risco crítico de viabilidade organizacional",
    sort_order: 10,
    axes: { flexibilidade: 15, controle: 30, integracao: 20, sustentacao: 15 },
    is_critical: true,
    auto_release_allowed: false,
    narrative: {
      summary:
        "Sinais convergentes de risco crítico de viabilidade organizacional: fragilidade financeira, perda de clientes, ruptura cultural e baixa capacidade de reação. Exige validação humana obrigatória e leitura cuidadosa do contexto.",
      signals: ["Resultados financeiros comprometidos", "Perda de clientes e de talentos", "Incapacidade de reagir a mudanças"],
      risks: ["Descontinuidade do negócio", "Decisões emergenciais sem base"],
      focus: ["Avaliação imediata de caixa e viabilidade", "Plano de recuperação com prioridades claras", "Acompanhamento próximo do analista APAS"],
    },
  },
];

/** Padrões organizacionais e indicadores críticos V1 (regras e afinidades calibráveis). */
export const V1_PATTERNS: DiagPattern[] = [
  {
    code: "centralizacao_no_lider",
    name: "Centralização no líder principal",
    kind: "pattern",
    severity: "alta",
    description: "Decisões e continuidade dependem do proprietário; delegação e mecanismos de sucessão frágeis.",
    rule: { all: [
      { type: "question", code: "L01", op: "<", value: 45 },
      { type: "question", code: "L08", op: "<", value: 50 },
      { type: "question", code: "PE06", op: "<", value: 50 },
    ] },
    stage_affinity: { namoro: 0.6, infancia: 1, toca_toca: 0.8, adolescencia: 0.2, plenitude: -0.8, estabilidade: -0.5, aristocracia: -0.3, burocracia: -0.3 },
    active: true,
    sort_order: 1,
  },
  {
    code: "crescimento_sem_estrutura",
    name: "Crescimento sem estrutura",
    kind: "pattern",
    severity: "alta",
    description: "Abertura a oportunidades e mercado elevada, com processos frágeis e pouco foco.",
    rule: { all: [
      { type: "dimension", code: "P", op: "<", value: 50 },
      { type: "dimension", code: "M", op: ">=", value: 55 },
      { type: "question", code: "E07", op: "<", value: 50 },
    ] },
    stage_affinity: { toca_toca: 1, infancia: 0.5, adolescencia: 0.3, plenitude: -0.7, estabilidade: -0.5, aristocracia: -0.6, burocracia: -0.8 },
    active: true,
    sort_order: 2,
  },
  {
    code: "profissionalizacao_em_curso",
    name: "Profissionalização em curso",
    kind: "pattern",
    severity: "media",
    description: "Gestão e delegação avançam enquanto integração e tratamento de conflitos ainda amadurecem.",
    rule: { all: [
      { type: "dimension", code: "G", op: ">=", value: 55 },
      { type: "question", code: "L02", op: ">=", value: 55 },
      { type: "question", code: "C07", op: "<", value: 65 },
      { type: "dimension", code: "CO", op: "<", value: 70 },
    ] },
    stage_affinity: { adolescencia: 1, toca_toca: 0.3, plenitude: 0.2, namoro: -0.5, burocracia: -0.4 },
    active: true,
    sort_order: 3,
  },
  {
    code: "equilibrio_maduro",
    name: "Equilíbrio maduro",
    kind: "pattern",
    severity: "baixa",
    description: "Todas as dimensões em nível adequado ou forte, com adaptação e sustentação simultâneas.",
    rule: { all: [
      { type: "axis", code: "flexibilidade", op: ">=", value: 70 },
      { type: "axis", code: "controle", op: ">=", value: 70 },
      { type: "axis", code: "integracao", op: ">=", value: 70 },
      { type: "axis", code: "sustentacao", op: ">=", value: 70 },
    ] },
    stage_affinity: { plenitude: 1, estabilidade: 0.4, adolescencia: 0.2, namoro: -1, infancia: -1, toca_toca: -0.6, pre_burocracia: -1, burocracia: -1, declinio: -1 },
    active: true,
    sort_order: 4,
  },
  {
    code: "conforto_e_perda_de_agilidade",
    name: "Conforto e perda de agilidade",
    kind: "pattern",
    severity: "media",
    description: "Gestão, processos e resultados sólidos, mas baixa disposição para mudar e antecipar o mercado.",
    rule: { all: [
      { type: "dimension", code: "G", op: ">=", value: 60 },
      { type: "dimension", code: "R", op: ">=", value: 60 },
      { type: "dimension", code: "I", op: "<", value: 50 },
      { type: "question", code: "M03", op: "<", value: 50 },
    ] },
    stage_affinity: { estabilidade: 1, aristocracia: 0.8, plenitude: -0.3, toca_toca: -1, namoro: -0.8 },
    active: true,
    sort_order: 5,
  },
  {
    code: "formalismo_sem_resultado",
    name: "Formalismo sem resultado",
    kind: "pattern",
    severity: "alta",
    description: "Controles e procedimentos fortes convivem com resultados fracos e pouca inovação.",
    rule: { all: [
      { type: "dimension", code: "P", op: ">=", value: 60 },
      { type: "dimension", code: "R", op: "<", value: 50 },
      { type: "dimension", code: "I", op: "<", value: 45 },
      { type: "question", code: "C06", op: "<", value: 45 },
    ] },
    stage_affinity: { aristocracia: 0.6, pre_burocracia: 0.8, burocracia: 1, plenitude: -1, toca_toca: -0.8 },
    active: true,
    sort_order: 6,
  },
  {
    code: "clima_de_culpa",
    name: "Clima de culpa e recriminação",
    kind: "pattern",
    severity: "alta",
    description: "Problemas não podem ser expostos com segurança; conflitos e busca de culpados predominam.",
    rule: { all: [
      { type: "question", code: "C02", op: "<", value: 45 },
      { type: "question", code: "C07", op: "<", value: 45 },
      { type: "question", code: "L07", op: "<", value: 50 },
      { type: "question", code: "CO06", op: "<", value: 50 },
    ] },
    stage_affinity: { pre_burocracia: 1, burocracia: 0.5, declinio: 0.4, plenitude: -0.8, estabilidade: -0.4 },
    active: true,
    sort_order: 7,
  },
  {
    code: "desconexao_com_mercado",
    name: "Desconexão com o mercado",
    kind: "pattern",
    severity: "alta",
    description: "Baixa leitura de clientes e concorrentes e pouca capacidade de adaptar a oferta.",
    rule: { all: [
      { type: "dimension", code: "M", op: "<", value: 45 },
      { type: "question", code: "M05", op: "<", value: 45 },
      { type: "question", code: "I03", op: "<", value: 45 },
    ] },
    stage_affinity: { aristocracia: 0.6, burocracia: 0.8, declinio: 0.8, toca_toca: -0.6, namoro: -0.3, plenitude: -0.8 },
    active: true,
    sort_order: 8,
  },
  {
    code: "fragilidade_financeira",
    name: "Fragilidade financeira",
    kind: "pattern",
    severity: "critica",
    description: "Rentabilidade, controle de custos e sustentabilidade do modelo comprometidos.",
    rule: { all: [
      { type: "dimension", code: "R", op: "<", value: 45 },
      { type: "question", code: "R04", op: "<", value: 45 },
      { type: "question", code: "R07", op: "<", value: 45 },
    ] },
    stage_affinity: { infancia: 0.5, declinio: 1, pre_burocracia: 0.4, namoro: 0.3, plenitude: -1, estabilidade: -0.8, aristocracia: -0.3 },
    active: true,
    sort_order: 9,
  },
  {
    code: "visao_sem_execucao",
    name: "Visão sem execução",
    kind: "pattern",
    severity: "media",
    description: "Clareza de propósito e diferencial, mas gestão, processos e resultados ainda incipientes.",
    rule: { all: [
      { type: "question", code: "E05", op: ">=", value: 60 },
      { type: "dimension", code: "G", op: "<", value: 45 },
      { type: "dimension", code: "P", op: "<", value: 45 },
      { type: "dimension", code: "R", op: "<", value: 50 },
    ] },
    stage_affinity: { namoro: 1, infancia: 0.5, toca_toca: 0.2, plenitude: -0.8, estabilidade: -0.6, burocracia: -0.6 },
    active: true,
    sort_order: 10,
  },
  {
    code: "silos_internos",
    name: "Silos internos",
    kind: "pattern",
    severity: "media",
    description: "Informação não circula entre áreas e conflitos ficam sem tratamento.",
    rule: { all: [
      { type: "question", code: "CO04", op: "<", value: 45 },
      { type: "question", code: "CO01", op: "<", value: 50 },
      { type: "question", code: "C07", op: "<", value: 55 },
    ] },
    stage_affinity: { adolescencia: 0.7, pre_burocracia: 0.6, burocracia: 0.5, aristocracia: 0.3, plenitude: -0.6 },
    active: true,
    sort_order: 11,
  },
  {
    code: "capacidade_de_adaptacao",
    name: "Capacidade de adaptação",
    kind: "pattern",
    severity: "baixa",
    description: "Empresa revisa estratégia, testa ideias e muda práticas com agilidade.",
    rule: { all: [
      { type: "dimension", code: "I", op: ">=", value: 65 },
      { type: "question", code: "M05", op: ">=", value: 60 },
      { type: "question", code: "E06", op: ">=", value: 60 },
      { type: "question", code: "C06", op: ">=", value: 60 },
    ] },
    stage_affinity: { plenitude: 0.6, toca_toca: 0.5, adolescencia: 0.4, aristocracia: -0.8, burocracia: -1, declinio: -0.8, pre_burocracia: -0.6 },
    active: true,
    sort_order: 12,
  },
  // ---- Indicadores críticos ----
  {
    code: "dependencia_critica_do_lider",
    name: "Dependência crítica do líder",
    kind: "critical",
    severity: "alta",
    description: "A empresa não funciona sem o líder principal e não há mecanismos para reduzir dependência de pessoas-chave.",
    rule: { all: [
      { type: "question", code: "L08", op: "<=", value: 25 },
      { type: "question", code: "PE06", op: "<=", value: 25 },
    ] },
    stage_affinity: { infancia: 0.8, toca_toca: 0.5, namoro: 0.4, declinio: 0.3, plenitude: -0.8, estabilidade: -0.5 },
    active: true,
    sort_order: 20,
  },
  {
    code: "risco_financeiro",
    name: "Risco financeiro",
    kind: "critical",
    severity: "critica",
    description: "Crescimento não sustentável e dúvida sobre a capacidade de manter o modelo de negócio.",
    rule: { any: [
      { type: "dimension", code: "R", op: "<", value: 35 },
      { type: "question", code: "R07", op: "<=", value: 25 },
    ] },
    stage_affinity: { declinio: 1, infancia: 0.4, pre_burocracia: 0.3, plenitude: -1, estabilidade: -0.8, aristocracia: -0.4 },
    active: true,
    sort_order: 21,
  },
  {
    code: "perda_de_conexao_com_clientes",
    name: "Perda de conexão com clientes",
    kind: "critical",
    severity: "alta",
    description: "A empresa não acompanha necessidades, feedback nem mudanças do mercado.",
    rule: { all: [
      { type: "question", code: "M01", op: "<=", value: 25 },
      { type: "question", code: "M04", op: "<=", value: 25 },
      { type: "question", code: "M03", op: "<=", value: 30 },
    ] },
    stage_affinity: { declinio: 0.8, burocracia: 0.6, aristocracia: 0.4, plenitude: -0.8, toca_toca: -0.5 },
    active: true,
    sort_order: 22,
  },
  {
    code: "paralisia_decisoria",
    name: "Paralisia decisória",
    kind: "critical",
    severity: "alta",
    description: "Ideias não são testadas, mudanças não acontecem e o controle sufoca a decisão.",
    rule: { all: [
      { type: "question", code: "I02", op: "<=", value: 25 },
      { type: "question", code: "I03", op: "<=", value: 25 },
      { type: "question", code: "P07", op: "<=", value: 30 },
    ] },
    stage_affinity: { burocracia: 1, pre_burocracia: 0.5, aristocracia: 0.4, declinio: 0.4, plenitude: -1, toca_toca: -0.8 },
    active: true,
    sort_order: 23,
  },
  {
    code: "ruptura_cultural",
    name: "Ruptura cultural",
    kind: "critical",
    severity: "alta",
    description: "Incoerência entre discurso e prática, medo de expor problemas e conflitos sem solução.",
    rule: { all: [
      { type: "question", code: "C02", op: "<=", value: 25 },
      { type: "question", code: "C01", op: "<=", value: 30 },
      { type: "question", code: "C07", op: "<=", value: 30 },
    ] },
    stage_affinity: { pre_burocracia: 1, declinio: 0.6, burocracia: 0.3, plenitude: -1, estabilidade: -0.6 },
    active: true,
    sort_order: 24,
  },
  {
    code: "ausencia_de_gestao",
    name: "Ausência de gestão sistemática",
    kind: "critical",
    severity: "alta",
    description: "Sem indicadores, rotinas de acompanhamento nem processos definidos.",
    rule: { all: [
      { type: "dimension", code: "G", op: "<", value: 30 },
      { type: "dimension", code: "P", op: "<", value: 30 },
    ] },
    stage_affinity: { infancia: 0.7, namoro: 0.6, toca_toca: 0.4, declinio: 0.3, plenitude: -1, estabilidade: -0.8, burocracia: -0.8 },
    active: true,
    sort_order: 25,
  },
];

export const V1_ENGINE_CONFIG: EngineConfig = {
  version: "V1",
  status: "heuristica_v1_calibravel",
  affinityWeights: { axes: 0.4, patterns: 0.4, critical: 0.2 },
  axisDistanceWeights: { flexibilidade: 1, controle: 1, integracao: 1, sustentacao: 1 },
  ruleMargin: 15,
  transitionGap: 6,
  confidence: {
    separationFull: 12,
    naPenaltyStart: 0.1,
    naPenaltyMax: 0.3,
    naPenaltyPoints: 25,
    contradictionPenalty: 8,
    lowCoveragePenalty: 15,
    minDimensionCoverage: 0.5,
    levels: { alta: 70, media: 45 },
  },
  dimensionBands: { critico: 40, atencao: 60, adequado: 80 },
  criticalAlertActivation: 0.5,
};
