import type { Dimension } from "./instrument";

export type CombinationNarrative = {
  title: string;
  essence: string;
  best: string[];
  excess: string[];
  perceived: string;
  communication: string;
  decision: string;
  leadership: string;
  team: string;
  pressure: string;
  change: string;
  experiments: string[];
  profilePortrait?: string;
  situations?: { work: string; relationships: string; decisions: string; leadership: string };
};

export const FACTOR_SHORT: Record<Dimension, string> = {
  D: "movimento e decisão",
  I: "conexão e influência",
  S: "constância e cooperação",
  C: "critério e precisão",
};

export const COMBINATION_NARRATIVES: Record<string, CombinationNarrative> = {
  DI: {
    title: "Direção que mobiliza",
    essence: "Esta combinação sugere iniciativa e determinação apoiadas por comunicação e capacidade de envolver. Você pode ganhar energia ao transformar uma ideia em movimento e convidar outras pessoas a avançar junto.",
    best: ["Abre caminhos quando falta direção", "Comunica decisões com energia", "Mobiliza pessoas em torno de objetivos", "Enfrenta desafios sem perder presença social"],
    excess: ["Acelerar antes de consolidar acordos", "Prometer mais frentes do que o tempo comporta", "Confundir objetividade com pressão", "Perder interesse no acompanhamento depois do impulso inicial"],
    perceived: "Sua intenção pode ser gerar avanço e confiança. Em ritmos diferentes do seu, esse movimento também pode ser percebido como pressa, intensidade ou pouco espaço para ponderação.",
    communication: "Tende a comunicar com clareza, energia e poder de convencimento. A mensagem ganha ainda mais força quando inclui contexto, escuta e um fechamento objetivo dos acordos.",
    decision: "Pode decidir com rapidez e usar a conversa para testar adesão. Vale separar entusiasmo de evidência antes de assumir prazos ou riscos.",
    leadership: "Tende a dar direção, elevar a energia e desafiar o grupo. A liderança se amplia quando expectativas, limites e responsabilidades ficam explícitos.",
    team: "Contribui com ritmo e articulação. Pode fortalecer a colaboração dando espaço para vozes mais reservadas e acompanhando a execução depois do alinhamento.",
    pressure: "Sob pressão, velocidade e expressividade podem aumentar. Pausar para checar impacto, prioridade e fatos ajuda a preservar qualidade nas relações e nas decisões.",
    change: "Costuma receber mudanças como oportunidade de ação. O desafio pode estar menos em começar e mais em dar estrutura, continuidade e segurança à transição.",
    experiments: ["Encerrar cada conversa importante com responsável, prazo e critério de sucesso", "Fazer duas perguntas antes de defender a própria solução", "Escolher uma prioridade para acompanhar até a conclusão"],
  },
  ID: {
    title: "Influência que cria movimento",
    essence: "Esta combinação sugere facilidade para criar conexão e, a partir dela, assumir iniciativa. Você pode ganhar energia ao comunicar possibilidades, reunir pessoas e transformar entusiasmo em ação.",
    best: ["Cria adesão para ideias novas", "Torna ambientes mais dinâmicos", "Assume a frente quando percebe oportunidade", "Conecta pessoas e objetivos"],
    excess: ["Agir pelo entusiasmo antes de dimensionar riscos", "Disputar espaço sem perceber", "Abrir frentes demais", "Adiar detalhes e acompanhamentos"],
    perceived: "Sua intenção pode ser inspirar e destravar. Para algumas pessoas, a mesma energia pode parecer improviso, dominância da conversa ou mudança rápida de foco.",
    communication: "Tende a pensar e construir pela conversa. Mensagens curtas, exemplos concretos e registro dos combinados ajudam a transformar influência em entrega.",
    decision: "Pode decidir pela oportunidade e pela reação das pessoas. Critérios simples e um breve teste de realidade ajudam a proteger a qualidade da escolha.",
    leadership: "Tende a liderar por presença, persuasão e coragem para iniciar. Ganha consistência quando acompanha rotinas e oferece devolutivas específicas.",
    team: "Aproxima pessoas e traz movimento. Pode ampliar a contribuição distribuindo espaço e reconhecendo quem sustenta o trabalho nos bastidores.",
    pressure: "Sob pressão, pode falar mais, acelerar compromissos ou buscar saídas imediatas. Reduzir estímulos e ordenar prioridades favorece decisões mais estáveis.",
    change: "Tende a comunicar possibilidades e gerar entusiasmo pela mudança. O cuidado está em traduzir a visão em etapas, responsáveis e continuidade.",
    experiments: ["Converter ideias em três próximos passos visíveis", "Ouvir a pessoa mais silenciosa antes de decidir", "Revisar promessas no fim de cada semana"],
  },
  DS: {
    title: "Direção com sustentação",
    essence: "Esta combinação sugere firmeza para avançar e disposição para sustentar o que foi assumido. Você pode alternar urgência por resultado com cuidado para que o ritmo seja viável.",
    best: ["Transforma decisão em continuidade", "Protege compromissos importantes", "Oferece direção em momentos difíceis", "Mantém foco sem abandonar o grupo"],
    excess: ["Carregar responsabilidades em excesso", "Oscilar entre acelerar e conter", "Guardar incômodo até o limite", "Insistir em uma direção já assumida"],
    perceived: "Sua intenção pode ser dar segurança e garantir avanço. Em alguns contextos, pode parecer controle, resistência a revisões ou firmeza difícil de questionar.",
    communication: "Tende a ser direto sem buscar exposição constante. Explicitar motivos e abrir tempo para reação reduz interpretações equivocadas.",
    decision: "Pode decidir com firmeza e sustentar a escolha. Vale definir antecipadamente quais sinais justificariam rever o caminho.",
    leadership: "Tende a combinar cobrança e proteção. A liderança se fortalece quando não assume sozinho o que precisa ser delegado.",
    team: "Oferece estabilidade e orientação. Pode estimular autonomia deixando mais claro o espaço de decisão de cada pessoa.",
    pressure: "Sob pressão, pode endurecer posições ou absorver trabalho para garantir a entrega. Dividir riscos e pedir apoio cedo protege energia e vínculo.",
    change: "Aceita mudanças quando enxerga propósito e possibilidade de execução. Um plano de transição ajuda a reconciliar velocidade e sustentação.",
    experiments: ["Definir sinais objetivos para revisar uma decisão", "Delegar uma entrega crítica com checkpoints", "Nomear um desconforto antes que ele se acumule"],
  },
  DC: {
    title: "Direção com critério",
    essence: "Esta combinação sugere foco em resultado apoiado por análise e padrão de qualidade. Você pode avançar com firmeza sem abrir mão de fundamentos relevantes.",
    best: ["Decide problemas complexos com objetividade", "Eleva padrões de entrega", "Identifica riscos com rapidez", "Transforma análise em ação"],
    excess: ["Elevar demais a exigência", "Comunicar correções sem contexto", "Centralizar decisões críticas", "Tratar divergências como falhas de lógica"],
    perceived: "Sua intenção pode ser proteger resultado e qualidade. O mesmo rigor pode ser percebido como dureza, crítica ou pouco espaço para aprender durante o percurso.",
    communication: "Tende a valorizar precisão e objetividade. Explicar prioridade, impacto humano e margem de experimentação torna a mensagem mais acessível.",
    decision: "Pode combinar velocidade com análise seletiva. Definir qual nível de evidência é suficiente evita tanto precipitação quanto excesso de controle.",
    leadership: "Tende a liderar por metas e padrões claros. Reconhecer avanços, além de apontar lacunas, amplia segurança e autonomia.",
    team: "Contribui com foco e consistência técnica. Pode fortalecer cooperação diferenciando erro de aprendizagem, descuido e falta de recurso.",
    pressure: "Sob pressão, cobrança e criticidade podem subir. Uma pausa para ordenar fatos, pessoas e consequência reduz respostas excessivamente duras.",
    change: "Tende a apoiar mudanças que tragam ganho objetivo e lógica consistente. Pilotos curtos podem oferecer evidência sem paralisar o movimento.",
    experiments: ["Definir o padrão suficiente antes de começar", "Reconhecer uma contribuição antes de corrigir", "Testar uma hipótese em pequena escala"],
  },
  IS: {
    title: "Conexão que sustenta",
    essence: "Esta combinação sugere comunicação próxima apoiada por constância e cuidado com vínculos. Você pode criar ambientes em que as pessoas se sintam incluídas e dispostas a colaborar.",
    best: ["Constrói confiança com naturalidade", "Percebe o clima do grupo", "Mantém pessoas conectadas", "Comunica mudanças com acolhimento"],
    excess: ["Evitar conversas que possam desagradar", "Assumir compromissos para preservar harmonia", "Demorar a estabelecer limites", "Priorizar clima acima da clareza"],
    perceived: "Sua intenção pode ser incluir e apoiar. Em certas situações, pode ser percebida como dificuldade de confrontar, excesso de concessão ou falta de prioridade explícita.",
    communication: "Tende a favorecer diálogo, proximidade e escuta. Nomear expectativas e discordâncias com a mesma clareza usada para acolher fortalece sua mensagem.",
    decision: "Pode considerar primeiro o impacto sobre as pessoas. Prazos e critérios ajudam a evitar que a busca de concordância adie escolhas necessárias.",
    leadership: "Tende a liderar por vínculo, participação e segurança. A liderança cresce quando cuidado também inclui cobrança e consequência.",
    team: "É uma combinação naturalmente orientada à colaboração. Preservar limites evita que disponibilidade se transforme em sobrecarga.",
    pressure: "Sob pressão, pode buscar aprovação ou silenciar desconfortos. Conversas diretas e respeitosas reduzem desgaste acumulado.",
    change: "Tende a apoiar mudanças quando as pessoas entendem o sentido e recebem suporte. Pode contribuir traduzindo impacto e construindo adesão gradual.",
    experiments: ["Fazer um pedido claro em vez de oferecer ajuda primeiro", "Registrar discordâncias e próximos passos", "Reservar tempo antes de aceitar uma nova demanda"],
  },
  IC: {
    title: "Influência com consistência",
    essence: "Esta combinação sugere capacidade de comunicar ideias e sustentá-las com lógica, dados ou preparo. Você pode aproximar pessoas de temas complexos sem perder a qualidade da mensagem.",
    best: ["Traduz complexidade com clareza", "Apresenta ideias de modo envolvente", "Conecta argumentos e pessoas", "Adapta a linguagem sem perder critério"],
    excess: ["Alongar explicações para garantir aceitação", "Oscilar entre espontaneidade e autocorreção", "Buscar validação para ideias já analisadas", "Perder o foco em detalhes da apresentação"],
    perceived: "Sua intenção pode ser tornar a proposta clara e convincente. Dependendo do contexto, pode ser percebida como excesso de elaboração ou necessidade de controlar a interpretação.",
    communication: "Tende a combinar presença e conteúdo. Começar pela mensagem central e ajustar a profundidade ao público aumenta impacto.",
    decision: "Pode alternar intuição social e verificação técnica. Tornar critérios explícitos ajuda a fechar decisões sem reabrir o tema muitas vezes.",
    leadership: "Tende a liderar explicando, envolvendo e qualificando. Delegar sem prescrever cada detalhe favorece autonomia.",
    team: "Contribui conectando diferentes linguagens e perspectivas. Pode cuidar para que análise e narrativa não substituam decisões práticas.",
    pressure: "Sob pressão, pode falar demais ou aprofundar detalhes para recuperar segurança. Sintetizar fatos, escolha e próximo passo reduz ruído.",
    change: "Tende a comunicar bem o sentido da mudança e antecipar dúvidas. Pilotos e ciclos de retorno ajudam a equilibrar adesão e precisão.",
    experiments: ["Resumir propostas em uma frase antes dos detalhes", "Definir prazo para encerrar a análise", "Delegar resultado e critério, não o caminho completo"],
  },
  SD: {
    title: "Constância com firmeza",
    essence: "Esta combinação sugere um ritmo estável que pode ganhar firmeza quando o contexto exige. Você tende a sustentar compromissos e assumir direção sem precisar ocupar o centro o tempo todo.",
    best: ["Mantém entregas em situações exigentes", "Age com firmeza quando necessário", "Protege continuidade e confiança", "Transforma compromisso em execução"],
    excess: ["Adiar posicionamentos até a urgência", "Assumir problemas sem dividir", "Tornar-se inflexível depois de decidir", "Acumular pressão silenciosamente"],
    perceived: "Sua intenção pode ser preservar estabilidade e resolver. Quando limites aparecem tarde, outras pessoas podem perceber uma mudança brusca de paciência para firmeza.",
    communication: "Tende a observar antes de falar e ser claro quando se posiciona. Antecipar necessidades e limites evita mensagens tardias ou intensas.",
    decision: "Pode amadurecer escolhas e agir com determinação depois de convencido. Estabelecer um prazo para decidir protege o ritmo sem gerar demora.",
    leadership: "Tende a oferecer segurança, consistência e firmeza prática. Compartilhar a direção mais cedo ajuda o grupo a participar.",
    team: "Contribui como ponto de apoio e execução confiável. Pode evitar assumir tarefas que pertencem a outras pessoas.",
    pressure: "Sob pressão, pode suportar muito antes de reagir com dureza. Sinalizar capacidade, risco e necessidade de ajuda com antecedência preserva relações.",
    change: "Tende a aderir quando entende impacto e caminho. Pode ser uma ponte valiosa entre decisão e implementação sustentável.",
    experiments: ["Comunicar um limite no primeiro sinal de sobrecarga", "Definir data para decisões adiadas", "Convidar o time a construir o plano antes de executá-lo"],
  },
  SI: {
    title: "Constância que aproxima",
    essence: "Esta combinação sugere cuidado com relações apoiado por uma comunicação acolhedora. Você pode contribuir para que pessoas cooperem, mantenham confiança e atravessem o cotidiano com mais conexão.",
    best: ["Escuta e acolhe perspectivas", "Sustenta um clima cooperativo", "Integra pessoas ao grupo", "Mantém comunicação próxima no dia a dia"],
    excess: ["Colocar necessidades alheias antes das próprias", "Evitar rupturas necessárias", "Demorar a cobrar acordos", "Depender demais de harmonia para avançar"],
    perceived: "Sua intenção pode ser apoiar e manter união. Em contextos que pedem decisões difíceis, pode ser percebida como hesitação ou falta de firmeza.",
    communication: "Tende a criar segurança para o diálogo. Mensagens com pedido, prazo e consequência ajudam a preservar vínculo sem perder objetividade.",
    decision: "Pode ouvir amplamente e considerar o impacto coletivo. Definir quem precisa ser consultado evita transformar participação em adiamento.",
    leadership: "Tende a liderar por confiança, disponibilidade e exemplo. A liderança cresce quando expectativas são ditas antes das frustrações.",
    team: "Contribui de forma agregadora e consistente. Limites claros protegem sua energia e estimulam reciprocidade.",
    pressure: "Sob pressão, pode absorver tensão e minimizar o próprio desconforto. Nomear fatos e pedir apoio reduz desgaste invisível.",
    change: "Tende a facilitar transições quando pode preparar pessoas e vínculos. Pequenas experiências ajudam a construir confiança no novo.",
    experiments: ["Transformar uma expectativa silenciosa em pedido claro", "Dizer não a uma demanda de baixo valor", "Conduzir uma conversa difícil enquanto o tema ainda é pequeno"],
  },
  SC: {
    title: "Constância com precisão",
    essence: "Esta combinação sugere cuidado com continuidade apoiado por método e atenção à qualidade. Você pode criar ambientes confiáveis, organizados e menos sujeitos a improvisos desnecessários.",
    best: ["Sustenta padrões ao longo do tempo", "Percebe riscos antes que cresçam", "Organiza rotinas confiáveis", "Entrega com cuidado e consistência"],
    excess: ["Resistir a mudanças pouco estruturadas", "Manter processos além da utilidade", "Guardar dúvidas em vez de testá-las", "Buscar segurança antes de experimentar"],
    perceived: "Sua intenção pode ser proteger qualidade e estabilidade. Para ritmos mais rápidos, isso pode parecer cautela excessiva, rigidez ou demora.",
    communication: "Tende a comunicar com cuidado e base concreta. Antecipar conclusões antes dos detalhes facilita a compreensão de públicos diferentes.",
    decision: "Pode decidir depois de organizar informação e impactos. Um critério de suficiência ajuda a evitar espera por segurança completa.",
    leadership: "Tende a liderar por método, previsibilidade e coerência. Abrir espaço para experimentação mantém o padrão sem limitar inovação.",
    team: "Oferece apoio, memória e qualidade operacional. Pode tornar visível seu raciocínio para que o grupo não interprete silêncio como resistência.",
    pressure: "Sob pressão, pode aumentar conferências e se retrair. Distinguir risco real de desconforto com a incerteza ajuda a priorizar.",
    change: "Tende a apoiar mudanças planejadas, testadas e bem comunicadas. Pode contribuir transformando novidade em rotina sustentável.",
    experiments: ["Definir o mínimo seguro para iniciar", "Compartilhar uma análise ainda em construção", "Eliminar uma rotina que não protege mais nenhum risco relevante"],
  },
  CD: {
    title: "Critério que decide",
    essence: "Esta combinação sugere análise cuidadosa com capacidade de assumir direção. Você pode reduzir riscos sem perder de vista resultado, especialmente em situações que exigem precisão e firmeza.",
    best: ["Decide com base consistente", "Enfrenta problemas técnicos difíceis", "Protege qualidade e resultado", "Questiona premissas antes de avançar"],
    excess: ["Elevar o padrão além da necessidade", "Ser direto ao apontar falhas", "Centralizar temas complexos", "Desconsiderar aspectos relacionais da decisão"],
    perceived: "Sua intenção pode ser garantir uma solução sólida. O mesmo foco pode ser percebido como crítica, distância ou pouca abertura para caminhos alternativos.",
    communication: "Tende a preferir argumentos objetivos e bem estruturados. Explicar impacto, intenção e margem de diálogo aproxima pessoas da análise.",
    decision: "Pode analisar profundamente e concluir com firmeza. Definir o que é reversível permite decisões mais rápidas onde o risco é controlado.",
    leadership: "Tende a liderar por competência, padrão e clareza. Reconhecer processo e progresso, não apenas resultado final, amplia confiança.",
    team: "Contribui com rigor e resolução. Pode convidar outras pessoas a construir critérios em vez de apenas receber a avaliação pronta.",
    pressure: "Sob pressão, exigência e controle podem aumentar. Priorizar riscos críticos e flexibilizar o restante protege foco e relação.",
    change: "Tende a apoiar mudanças com fundamento e benefício demonstrável. Experimentos reversíveis reduzem a necessidade de certeza antecipada.",
    experiments: ["Classificar decisões entre reversíveis e irreversíveis", "Perguntar antes de corrigir", "Escolher dois critérios críticos e flexibilizar os demais"],
  },
  CI: {
    title: "Precisão que comunica",
    essence: "Esta combinação sugere busca de qualidade acompanhada por capacidade de traduzir e compartilhar ideias. Você pode tornar temas complexos mais compreensíveis e confiáveis para outras pessoas.",
    best: ["Transforma informação em entendimento", "Prepara mensagens consistentes", "Conecta conhecimento e público", "Antecipa dúvidas relevantes"],
    excess: ["Explicar além do necessário", "Buscar aprovação para validar a análise", "Revisar excessivamente a forma", "Oscilar entre reserva e exposição intensa"],
    perceived: "Sua intenção pode ser oferecer clareza e segurança. Dependendo do momento, pode ser percebida como excesso de detalhe ou dificuldade de simplificar.",
    communication: "Tende a preparar bem o conteúdo e adaptar sua apresentação. Começar pela conclusão ajuda o público a localizar os detalhes.",
    decision: "Pode combinar evidência e leitura de audiência. Separar fatos, preferências e receios torna a escolha mais nítida.",
    leadership: "Tende a liderar por conhecimento e capacidade de explicar. Aceitar soluções diferentes que atendam aos critérios favorece autonomia.",
    team: "Contribui como ponte entre técnica e relacionamento. Pode equilibrar preparação individual com construção conjunta.",
    pressure: "Sob pressão, pode revisar demais ou falar para organizar o pensamento. Um roteiro curto ajuda a proteger tempo e clareza.",
    change: "Tende a apoiar mudanças que façam sentido e possam ser bem explicadas. Pode ajudar a traduzir razões, riscos e critérios para o grupo.",
    experiments: ["Apresentar a conclusão nos primeiros trinta segundos", "Publicar uma versão boa antes da perfeita", "Perguntar de quanto detalhe o interlocutor precisa"],
  },
  CS: {
    title: "Precisão que sustenta",
    essence: "Esta combinação sugere atenção a critérios apoiada por paciência e continuidade. Você pode proteger a qualidade ao longo do tempo e construir confiança por meio de entregas consistentes.",
    best: ["Mantém qualidade de forma previsível", "Organiza conhecimento e processos", "Escuta antes de concluir", "Reduz riscos com cuidado"],
    excess: ["Adiar decisões esperando mais segurança", "Evitar confrontos sobre padrões", "Apegar-se a métodos conhecidos", "Revisar além do impacto real"],
    perceived: "Sua intenção pode ser cuidar da qualidade e evitar riscos. Em cenários velozes, pode ser percebida como reserva, resistência ou excesso de cautela.",
    communication: "Tende a ser ponderado e específico. Tornar a conclusão visível e comunicar dúvidas cedo evita que o silêncio seja mal interpretado.",
    decision: "Pode comparar opções com profundidade e considerar consequências. Prazos e critérios de suficiência ajudam a concluir.",
    leadership: "Tende a liderar por coerência, método e cuidado. Oferecer direção explícita em momentos ambíguos aumenta segurança do grupo.",
    team: "Contribui com confiabilidade, escuta e memória técnica. Pode ocupar mais espaço quando sua análise precisa influenciar o rumo.",
    pressure: "Sob pressão, pode se retrair, conferir mais ou manter rotinas conhecidas. Explicitar prioridades ajuda a usar energia onde realmente importa.",
    change: "Tende a preferir transições planejadas e fundamentadas. Pode ser essencial para converter uma mudança em processo confiável.",
    experiments: ["Compartilhar uma preocupação antes de concluir a análise", "Definir prazo e critério para fechar uma decisão", "Testar uma mudança pequena sem redesenhar todo o processo"],
  },
};