import { AlertTriangle, CalendarDays, CheckCircle2, Compass, Focus, Gauge, MessageCircle, Network, RefreshCw, Sprout, Users } from "lucide-react";
import type { ReactNode } from "react";
import type { ScoreResult } from "@/lib/disc/scoring";
import { DIMENSIONS, DIMENSION_NAMES } from "@/lib/disc/instrument";
import { DIMENSION_CONTENT } from "@/lib/disc/content";
import { COMBINATION_NARRATIVES } from "@/lib/disc/report-content";

type TechnicalAssessment = { id: string; candidate_name: string; status: string; instrument_version?: string | null; created_at: string; started_at?: string | null; submitted_at?: string | null; consent_accepted_at?: string | null; organizations?: { name?: string | null } | null };

function duration(start?: string | null, end?: string | null) {
  if (!start || !end) return "Não disponível";
  const minutes = Math.max(0, Math.round((new Date(end).getTime() - new Date(start).getTime()) / 60000));
  return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)}h ${minutes % 60}min`;
}

function TechnicalPage({ number, title, kicker, children, dark = false }: { number: number; title: string; kicker: string; children: ReactNode; dark?: boolean }) {
  return <section className={`disc-tech-page ${dark ? "disc-tech-page-dark" : ""}`}><header><span className="disc-tech-brand"><strong>APAS</strong> SOLUÇÕES</span><span>Relatório técnico do especialista</span></header><main><p className="disc-tech-kicker">{kicker}</p><h1>{title}</h1>{children}</main><footer><span>Uso confidencial · Especialista autorizado</span><span>{String(number).padStart(2, "0")}</span></footer></section>;
}

function ProfileMatrix({ scores }: { scores: ScoreResult }) {
  const profiles = [{ label: "Natural", values: scores.natural.percent }, { label: "Adaptado", values: scores.adapted.percent }, { label: "Social", values: scores.social.percent }];
  return <div className="disc-tech-profiles">{profiles.map((profile) => <section key={profile.label}><h3>{profile.label}</h3>{DIMENSIONS.map((d) => <div className="disc-tech-bar" key={d}><span>{d}</span><div><i className={`disc-factor-${d.toLowerCase()}`} style={{ width: `${profile.values[d]}%` }} /></div><strong>{profile.values[d]}%</strong></div>)}</section>)}</div>;
}

export function DiscTechnicalReport({ assessment, scores, computedAt }: { assessment: TechnicalAssessment; scores: ScoreResult; computedAt?: string | null }) {
  const narrative = COMBINATION_NARRATIVES[scores.combination] ?? COMBINATION_NARRATIVES[`${scores.predominant}${scores.secondary}`];
  if (!narrative) return null;
  const primary = DIMENSION_CONTENT[scores.predominant];
  const secondary = DIMENSION_CONTENT[scores.secondary];
  const adaptation = scores.adaptationAlert ? "A distância entre os perfis merece investigação contextual. Pode representar flexibilidade diante das demandas ou esforço de adaptação prolongado; não concluir sem exemplos concretos." : "A distância entre os perfis não acionou alerta automático. Ainda assim, valide em quais ambientes a pessoa amplia, reduz ou alterna comportamentos.";
  return <article className="disc-technical-report" aria-label={`Relatório técnico de ${assessment.candidate_name}`}>
    <TechnicalPage number={1} kicker="Síntese protegida" title="Leitura técnica APAS DISC" dark><div className="disc-tech-cover"><div><p>Avaliado</p><h2>{assessment.candidate_name}</h2><span>{assessment.organizations?.name || "Aplicação individual"}</span></div><div className="disc-tech-combo"><strong>{scores.combination}</strong><span>{scores.predominant} primário / {scores.secondary} secundário</span><p>{narrative.title}</p></div></div><div className="disc-tech-meta"><p><CalendarDays />Aplicação<br/><strong>{new Date(assessment.created_at).toLocaleString("pt-BR")}</strong></p><p><Gauge />Duração<br/><strong>{duration(assessment.started_at, assessment.submitted_at)}</strong></p><p><CheckCircle2 />Cobertura<br/><strong>{scores.answeredItems} de {scores.totalItems} blocos</strong></p><p><Compass />Instrumento<br/><strong>{assessment.instrument_version || "APAS DISC 1.2"}</strong></p></div><p className="disc-tech-confidential">Documento de apoio à devolutiva. Não contém respostas brutas, perguntas, fórmulas, pesos ou regras proprietárias.</p></TechnicalPage>
    <TechnicalPage number={2} kicker="Perfis e intensidade" title="Três perspectivas para interpretar em conjunto"><ProfileMatrix scores={scores}/><div className="disc-tech-callout"><Gauge/><div><h3>Índice de adaptação · {scores.adaptationIndex}</h3><p>{adaptation}</p></div></div><div className="disc-tech-grid">{DIMENSIONS.map((d) => <div key={d}><strong>{d} · {DIMENSION_NAMES[d]}</strong><span>{scores.adapted.percent[d]}% adaptado</span><p>{DIMENSION_CONTENT[d].strengths[0]}. Em excesso, validar: {DIMENSION_CONTENT[d].attention[0].toLowerCase()}.</p></div>)}</div></TechnicalPage>
    <TechnicalPage number={3} kicker="Hipóteses de atuação" title="Combinação, contexto e impacto" dark><div className="disc-tech-lead"><strong>{scores.combination}</strong><div><h2>{narrative.title}</h2><p>{narrative.essence}</p></div></div><div className="disc-tech-themes"><section><MessageCircle/><h3>Comunicação</h3><p>{narrative.communication}</p></section><section><Compass/><h3>Liderança</h3><p>{narrative.leadership}</p></section><section><Focus/><h3>Decisão</h3><p>{narrative.decision}</p></section><section><Users/><h3>Equipe</h3><p>{narrative.team}</p></section><section><Gauge/><h3>Pressão</h3><p>{narrative.pressure}</p></section><section><RefreshCw/><h3>Mudança</h3><p>{narrative.change}</p></section></div></TechnicalPage>
    <TechnicalPage number={4} kicker="Validação humana" title="Pontos para aprofundar na devolutiva"><div className="disc-tech-validation"><section><AlertTriangle/><h3>Pontos a validar</h3><ul>{[...narrative.excess, ...primary.attention.slice(0, 2), ...secondary.attention.slice(0, 2)].map((item) => <li key={item}>{item}</li>)}</ul></section><section><MessageCircle/><h3>Perguntas de devolutiva</h3><ol><li>O que mais representa sua experiência atual? O que menos representa?</li><li>Em quais contextos seu comportamento muda mais?</li><li>Que exigências do ambiente consomem mais energia hoje?</li><li>Como outras pessoas descreveriam sua comunicação sob pressão?</li><li>Que exemplo recente confirma ou contradiz esta leitura?</li><li>Qual ajuste produziria maior impacto nos próximos 30 dias?</li></ol></section></div><div className="disc-tech-callout"><CheckCircle2/><div><h3>Critério de condução</h3><p>Trate cada leitura como hipótese. Diferencie preferência comportamental, competência, experiência, motivação e desempenho. Procure exemplos observáveis antes de consolidar qualquer interpretação.</p></div></div></TechnicalPage>
    <TechnicalPage number={5} kicker="Desenvolvimento aplicado" title="O que fazer, como fazer e acompanhar" dark><div className="disc-tech-followup">{narrative.experiments.map((item, index) => <section key={item}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{["Escolher um comportamento", "Praticar em contexto", "Observar e ajustar"][index]}</h3><p>{item}</p><small>{["Defina uma situação real e um resultado observável.", "Combine apoio, frequência e prazo de experimentação.", "Recolha retorno de alguém e registre evidências."][index]}</small></div></section>)}</div><div className="disc-tech-plan"><Sprout/><div><h3>Plano de acompanhamento</h3><p><strong>7 dias:</strong> alinhar comportamento, contexto e indicador.</p><p><strong>15 dias:</strong> revisar experiência, barreiras e efeito percebido.</p><p><strong>30 dias:</strong> comparar evidências e decidir manutenção, ajuste ou novo experimento.</p></div></div><div className="disc-tech-checklist"><h3>Encerramento do especialista</h3><p>□ A pessoa se reconheceu na leitura, com exemplos.</p><p>□ Pontos de divergência foram registrados sem forçar concordância.</p><p>□ Uma ação prática, prazo e indicador foram acordados.</p><p>□ O acompanhamento foi combinado.</p></div><p className="disc-tech-confidential">Gerado em {computedAt ? new Date(computedAt).toLocaleString("pt-BR") : "data não disponível"} · ID {assessment.id}</p></TechnicalPage>
  </article>;
}